name: try1
channels:
  - nodefaults
dependencies:
  - astroid=2.2.5=py37_0
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - colorama=0.4.1=py37_0
  - isort=4.3.19=py37_0
  - mccabe=0.6.1=py37_1
  - numpy=1.16
  - numpy-base=1.16
  - pip=19.1.1=py37_0
  - pylint=2.3.1=py37_0
  - python=3.7
  - setuptools=41.0.1=py37_0
  - sqlite=3.28
  - wheel=0.33.4=py37_0
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - gast==0.2.2
    - google-pasta==0.1.6
    - grpcio==1.21.1
    - h5py==2.9.0
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - markdown==3.1.1
    - protobuf==3.7.1
    - six==1.12.0
    - tb-nightly==1.14.0a20190301
    - tensorflow==2.0.0a0
    - termcolor==1.1.0
    - tf-estimator-nightly==1.14.0.dev2019030115
    - werkzeug==0.15.4